# Generated by Django 5.2.2 on 2025-06-06 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="transcription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_file",
                to="audio.transcription",
            ),
        ),
    ]
