# Generated by Django 4.2.11 on 2025-06-07 14:06

import audio.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='is_video',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to=audio.models.audio_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'ogg', 'flac', 'aac', 'wma', 'aiff', 'mp4', 'mov', 'avi', 'mkv', 'webm', 'flv', 'wmv', 'm4v', '3gp'])]),
        ),
    ]
