# Generated by Django 5.2.2 on 2025-06-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0003_audiofile_is_video_alter_audiofile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="language_probability",
            field=models.FloatField(
                blank=True, help_text="Confidence score of detected language", null=True
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="segments",
            field=models.JSONField(
                blank=True,
                help_text="Detailed transcription segments with timestamps",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="word_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of words in transcription", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="language",
            field=models.CharField(
                default="en", help_text="Detected language code", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="text",
            field=models.TextField(
                blank=True, help_text="Full transcription text", null=True
            ),
        ),
    ]
