# Generated by Django 4.2.11 on 2025-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_transcription_language_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='model_used',
            field=models.CharField(choices=[('tiny', 'Tiny (Fastest, lowest accuracy)'), ('base', 'Base (Fast, lower accuracy)'), ('small', 'Small (Good balance)'), ('medium', 'Medium (Better accuracy)'), ('large', 'Large (Best accuracy, slowest)')], default='base', help_text='Whisper model used for transcription', max_length=10),
        ),
    ]
