# Generated by Django 4.2.23 on 2025-06-28 18:21

import audio.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_transcription_model_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(help_text='Original uploaded file (video or audio)', upload_to=audio.models.get_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'ogg', 'flac', 'aac', 'wma', 'aiff', 'mp4', 'mov', 'avi', 'mkv', 'webm', 'flv', 'wmv', 'm4v', '3gp'])])),
                ('extracted_audio', models.FileField(blank=True, help_text='Extracted audio file (for video uploads)', null=True, upload_to=audio.models.get_media_upload_path)),
                ('is_video', models.BooleanField(default=False, editable=False)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('sample_rate', models.IntegerField(blank=True, help_text='Sample rate in Hz', null=True)),
                ('channels', models.IntegerField(blank=True, help_text='Number of audio channels', null=True)),
                ('bitrate', models.IntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('video_codec', models.CharField(blank=True, max_length=50, null=True)),
                ('video_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('frame_rate', models.FloatField(blank=True, null=True)),
                ('audio_extracted', models.BooleanField(default=False, help_text='Whether audio was extracted from video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
            },
        ),
        migrations.AddField(
            model_name='transcription',
            name='has_speaker_diarization',
            field=models.BooleanField(default=False, help_text='Whether speaker diarization was performed'),
        ),
        migrations.AddField(
            model_name='transcription',
            name='speaker_segments',
            field=models.JSONField(blank=True, default=list, help_text='Segments with speaker information', null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='speakers',
            field=models.JSONField(blank=True, default=list, help_text='List of speakers with their display names and colors', null=True),
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='transcription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_file', to='audio.transcription'),
        ),
    ]
