# Generated by Django 4.2.23 on 2025-06-28 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('speaker_segments', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legacy User Transcription',
                'verbose_name_plural': 'Legacy User Transcriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
