# Generated by Django 4.2.11 on 2025-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_model_size',
            field=models.CharField(choices=[('tiny', 'Tiny (Fastest, lowest accuracy)'), ('base', 'Base (Fast, lower accuracy)'), ('small', 'Small (Good balance)'), ('medium', 'Medium (Better accuracy)'), ('large', 'Large (Best accuracy, slowest)')], default='base', help_text='Maximum model size allowed for this plan', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='supported_models',
            field=models.JSONField(default=list, help_text='List of supported Whisper models (tiny, base, small, medium, large)'),
        ),
    ]
