# Generated by Django 4.2.11 on 2025-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_max_model_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(help_text='Detailed description of the plan features'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(help_text='A short label for the plan, used in URLs and references', unique=True),
        ),
    ]
