# Generated by Django 4.2.23 on 2025-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscriptionplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='speaker_diarization_enabled',
            field=models.BooleanField(default=False, help_text='Whether this plan includes speaker diarization feature'),
        ),
    ]
